# Generated by Django 4.0.3 on 2022-04-10 20:52

from django.db import migrations, models
import django.db.models.deletion
import podcast.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Podcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to=podcast.models.podcasts_directory_path)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Подкаст',
                'verbose_name_plural': 'Подкасти',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PodcastSong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('release', models.IntegerField(default=0)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('cover', models.ImageField(upload_to='podcasts/')),
                ('audio', models.FileField(upload_to='podcasts/')),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('podcast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='podcast.podcast', verbose_name='Виконавець')),
            ],
            options={
                'verbose_name': 'Пісня подкасту',
                'verbose_name_plural': 'Пісні подкасту',
                'ordering': ['id'],
            },
        ),
    ]
