import Cover from "../../assets/img/PlayList/cover.png";

export const PlayListItems = [
  {
    id: 1,
    cover: `${Cover}`,
    band: "Один в каное",
    title: "В мене немає дому",
    playing: 9999,
    time: "2:30",
  },
  {
    id: 2,
    cover: `${Cover}`,
    band: "KLEFT",
    title: "На гачку",
    playing: 2123,
    time: "2:30",
  },
  {
    id: 3,
    cover: `${Cover}`,
    band: "Billie Jean",
    title: "Thriller 25 Sup...",
    playing: 122,
    time: "12:30",
  },
  {
    id: 4,
    cover: `${Cover}`,
    band: "Man-Gust",
    title: "Буряк",
    playing: 5222,
    time: "12:30",
  },
  {
    id: 5,
    cover: `${Cover}`,
    band: "Бумбокс",
    title: "Бета-каротин",
    playing: 122,
    time: "12:30",
  },
  {
    id: 6,
    cover: `${Cover}`,
    band: "Саша Чемеров",
    title: "Кохання до смерті",
    playing: 122,
    time: "12:30",
  },
  {
    id: 7,
    cover: `${Cover}`,
    band: "O.Torvald",
    title: "В подушках",
    playing: 122,
    time: "12:30",
  },
  {
    id: 8,
    cover: `${Cover}`,
    band: "Billie Jean",
    title: "Thriller 25 Sup...",
    playing: 122,
    time: "12:30",
  },
  {
    id: 9,
    cover: `${Cover}`,
    band: "Billie Jean",
    title: "Thriller 25 Sup...",
    playing: 122,
    time: "12:30",
  },
  {
    id: 10,
    cover: `${Cover}`,
    band: "Billie Jean",
    title: "Thriller 25 Sup...",
    playing: 122,
    time: "12:30",
  },
  {
    id: 11,
    cover: `${Cover}`,
    band: "Billie Jean",
    title: "Thriller 25 Sup...",
    playing: 122,
    time: "12:30",
  },
];
